"""make_cast_member_character_field_nullable

Revision ID: d9557c2cfcb6
Revises: 81a76dc1bddc
Create Date: 2025-09-27 10:16:12.899114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9557c2cfcb6'
down_revision = '81a76dc1bddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('character',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.alter_column('character',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
